### PR TITLE
fix(website): fix broken demo

### LINKED ISSUE #886: Website: demo broken with Grepper browser extension installed
https://addons.mozilla.org/en-GB/firefox/addon/grepper/
https://quick-lint-js.com/demo/
https://cdn.discordapp.com/attachments/640652660839677964/1039647971777716244/image.png

### PR DESCRIPTION
**Pull request by clegoz**
Fixes #886

### CODE REVIEW

**Review by strager — APPROVED** [review]
This does fix the layout bug. But squigglies still don't appear.

**Comment by strager** [comment]
Shall I merge this even though it doesn't fix everything?

**Comment by clegoz** [comment]
I don't see any issue like you mentioned. Could it be caused by wasm?

The only problem I see is the markings are little bit off. Adding `padding: 0` to `#code-input-marks-scroller` fixes it. I'll add this fix to the commit.

image

**Comment by strager** [comment]
Landed as commit 9fafaa963a22d05f6ed9e833ccaf4dc131723a9f. Sorry for the delay!

> This does fix the layout bug. But squigglies still don't appear.

I tested your patch again and it worked perfectly. I don't know what happened when I tested last time...

**Pull request closed without merging**
