### PR TITLE
Added documentation for E201

### PR DESCRIPTION
**Pull request by zomglings**
Just trying to help out.

### CODE REVIEW

**Comment by zomglings** [comment]
I have read and hereby agree to quick-lint-js' Contributor License Agreement (CLA-v1.md).

**Comment by zomglings** [comment]
recheck

**Comment by zomglings** [comment]
Had some trouble setting up emscripten for the quick-lint-js WASM target. Will try to figure it out later.

**Comment by strager** [comment]
I forgot about this PR and I documented E0201 myself. =X

**Pull request closed without merging**
