### PR TITLE
Added LibreJS support to website

### PR DESCRIPTION
**Pull request by Jasper-Hawks**
Specified the license in both quick-lint-js.mjs and editor.mjs
Fixed Issue: #189

### CODE REVIEW

**Comment by Jasper-Hawks** [comment]
I have read and hereby agree to quick-lint-js' Contributor License Agreement (CLA-v1.md).

**Comment by strager** [comment]
Looks good. Thanks for taking a stab at this task.

Did you test that the LibreJS browser extension does the right thing? Can you screenshot its UI?

What about the .wasm file? Does it need similar annotation?

**Comment by Jasper-Hawks** [comment]
The program list and blocks the scripts that are not compatible with LibreJS, if all the scripts are compatible then no scripts will be listed and they will all be executed.
librejs

**Comment by Jasper-Hawks** [comment]
The .wasm file doesn't appear to be blocked or accepted

**Comment by strager** [comment]
> The program list and blocks the scripts that are not compatible with LibreJS, if all the scripts are compatible then no scripts will be listed and they will all be executed.

What's it look like with your patch?

> The .wasm file doesn't appear to be blocked or accepted

That's probably because the .mjs files load the .wasm files without using `<script>` or `import`.

**Comment by Jasper-Hawks** [comment]
None of the scripts are blocked on any of the pages. I'll add the license tags to the .wasm file.

**Comment by Jasper-Hawks** [comment]
I'm looking through the files and I only see wasm-demo.h and wasm-demo.cpp. Would you like me to add the license tags to both?

**Comment by strager** [comment]
> I'm looking through the files and I only see wasm-demo.h and wasm-demo.cpp. Would you like me to add the license tags to both?

`wasm-demo.h` and `wasm-demo.cpp` are not served to web clients.

See website/demo/README.md for instructions on building the .wasm file.

> None of the scripts are blocked on any of the pages.

Okay. If annotating the .wasm file is unnecessary, I guess we don't need to do it.

I'll try out this patch tomorrow to get a feel for how LibreJS works.

**Comment by strager** [comment]
This patch doesn't seem to fully work. Some scripts are still blocked, so the demo doesn't work with LibreJS installed:

Screenshot from 2021-04-08 15-04-12

**Review by strager — CHANGES_REQUESTED** [review]
.

**Comment by strager** [comment]
@Jasper-Hawks Are you still working on this PR?

**Comment by Jasper-Hawks** [comment]
No. I've given up.

**Pull request closed without merging**
