### PR TITLE
#1013 updated quick-lint-js.html

### PR DESCRIPTION
**Pull request by Monib007**
Changed a variable that didn't exist.

### CODE REVIEW

**Comment by Monib007** [comment]
I have read and hereby agree to quick-lint-js' Contributor License Agreement (CLA-v1.md).

**Comment by Monib007** [comment]
recheck

**Comment by strager** [comment]
How did you test this change?

**Comment by jakecastelli** [comment]
@Monib007 that variable was mis-spelled on purpose in order to show case quick-lint-js

**Pull request closed without merging**
