### PR TITLE
feat(fe): error for missing expression in JSX prop

### PR DESCRIPTION
**Pull request by JPMoles**
Shows an error message on empty JSX props.

Issue: #986

### CODE REVIEW

**Comment by JPMoles** [comment]
I have read and hereby agree to quick-lint-js' Contributor License Agreement (CLA-v1.md).

**Comment by JPMoles** [comment]
recheck

**Review by strager — APPROVED** [review]
Nice and simple. Thanks!

**Comment by JPMoles** [comment]
Okay, the examples should be fixed now.

**Comment by strager** [comment]
Landed as commit 3a6d00c177aad868e47cdd56d962c79621373786.

**Pull request closed without merging**
