### PR TITLE
829 add ASAN_OPTIONS=detect_stack_use_after_return=1

### PR DESCRIPTION
**Pull request by AlekLefebvre**
Adds the ASAN_OPTIONS environment variable with the detect_stack_use_after_return=1 runtime flag. I validated that the flag is functional by temporarily adding code to trigger it.

### CODE REVIEW

**Comment by AlekLefebvre** [comment]
recheck

**Comment by AlekLefebvre** [comment]
I have read and hereby agree to quick-lint-js' Contributor License Agreement (CLA-v1.md).

**Comment by strager** [comment]
This looks great!

**Comment by strager** [comment]
Merged as commit 4d41ecb465f5649a20954047d0d4f6096981e78b.

**Pull request closed without merging**
