### PR TITLE
Document CLI on Website 

### PR DESCRIPTION
**Pull request by DGKSK8LIFE**
Completed PR to satisfy issue requirements. Feel free to suggest changes to the CSS, I hacked it together pretty quickly

#224

### CODE REVIEW

**Comment by DGKSK8LIFE** [comment]
I have read and hereby agree to quick-lint-js' Contributor License Agreement (CLA-v1.md).

**Review by DGKSK8LIFE — COMMENTED** [review]
Mistyped your username in the commit message. Anyways, I don't think that plaintext would be the most appealing option for CLI output documentation. Perhaps a CSS custom code block class? Or maybe just a GIF of the tool actually being used on a JS file. Either way, tell me what think about the work I've done so far, what changes you'd like to make, etc. Thanks @strager

**Comment by strager** [comment]
> I don't think that plaintext would be the most appealing option for CLI output documentation. Perhaps a CSS custom code block class?

Are you talking about the examples in the "EXAMPLE" section of `quick-lint-js.1`? Yeah, I'd like to see it formatted similar to the shell snippets on our [installation page](https://quick-lint-js.com/install.html#debian).

> Or maybe just a GIF of the tool actually being used on a JS file.

I don't think a GIF usage of a batch CLI tool would be helpful. At the very least, text in a GIF can't be copy-pasted.

> Either way, tell me what think about the work I've done so far, what changes you'd like to make, etc.

* The "Error Lists" section is poorly formatted. It should be in many paragraphs and definition lists, not three giant list items.
* The "Exit Status" section makes no sense. Where's the mention of exit status 0? What is "non-0 Batch mode"?
* The "Environment" section mentions `LC_ALL` in the example, but not in the list of variables.
* The "Example" section is missing.
* The page is missing a `<title>`.
* The page's `<meta name="description">` message is wrong.
* The use of bullet points for everything is odd to me, especially in the "Description" and "Error Lists" sections. Paragraphs and definition lists should be used in many places where bullet points are used now.
* References to sections should be hyperlinked. E.g. "See the "ERROR LISTS" section" should be clickable and navigate the user to the section on error lists.
* For "This Command has **two modes**", "Command" should be lower-case, and "two modes" should not be bold.
* In the description for `--output-format`, each format has two bullet points. They should have one each.
* Option names should be formatted consistently. Some mentions of `--lsp-server` are bold, and others are not. (I see that the `quick-lint-js.1` is guilty too; one spot isn't bold but I think it should be. Not your fault, of course.)
* References to the `quick-lint-js` command should be formatted consistently. Some references are bold, and others are not.
* In the description of `--output-format`, "func‐ tion" is broken but should be one word.

**Comment by DGKSK8LIFE** [comment]
> The use of bullet points for everything is odd to me, especially in the "Description" and "Error Lists" sections. Paragraphs and definition lists should be used in many places where bullet points are used now.

Doing this to establish a visual hierarchy in the docs. To be honest, I don't like the way the docs look overall. Going to research Groff.

**Comment by DGKSK8LIFE** [comment]
> In the description of --output-format, "func‐ tion" is broken but should be one word.

I believe this is due to the HTML linter I am using.

**Comment by DGKSK8LIFE** [comment]
@strager I'm happy to pass this on to someone else if they're willing to complete the task. Thanks

**Comment by strager** [comment]
Superseded by #243.

**Pull request closed without merging**
