### PR TITLE
Added <link rel=canonical> to the website

### PR DESCRIPTION
**Pull request by Youness-Asserare**

### CODE REVIEW

**Comment by Youness-Asserare** [comment]
I have read and hereby agree to quick-lint-js' Contributor License Agreement (CLA-v1.md).

**Comment by Youness-Asserare** [comment]
recheck

**Comment by strager** [comment]
How did you test this change?

**Comment by Youness-Asserare** [comment]
> How did you test this change?

I checked if it exists in some pages of the website inside the head tag

**Comment by strager** [comment]
> I checked if it exists in some pages of the website inside the head tag

Please test the *functionality*, or use a tool to approximate.

Search engines use the canonical `<link>` to remove `?utm_campaign=` crap from URLs. I don't know how to test this without publishing the changes to quick-lint-js.com.

There are online tools to check pages, such as this one: https://sitechecker.pro/canonical-url/ You need to publish the site somewhere online to make such a tool work. You should be able to host quick-lint-js' website using GitHub Pages or Netlify. (#274 would make this very easy for you, but it's not implemented.)

There might be offline tools you can use, but I don't know of any.

---

I don't think your implementation is correct, because it's missing `href`. That's why I asked about your testing methodology.

**Comment by Youness-Asserare** [comment]
I modified the pull request.
You are right ! my implementation was wrong.
I hosted the website in github pages and tested it with this online tool "https://seositecheckup.com/tools/canonical-tag-test".
I tried using the tool you recommended but it didn't work, it showed this error " Sitechecker bot is not allowed to crawl this website. "
but this i think this would work.

**Comment by Youness-Asserare** [comment]
hi strager ! can you check my pull request ?

**Comment by strager** [comment]
Looks great! Sorry for the delay.

**Pull request merged**
