### PR TITLE
Fix #967: Increase demonstration wrapper max-width

### LINKED ISSUE #967: Website home page broken with big font size
https://cdn.discordapp.com/attachments/835712135962296330/1093064469237747782/image.png

Set font size to 'very large' in Firefox, and visit https://quick-lint-js.com/.

### PR DESCRIPTION
**Pull request by abhaykv04**

### CODE REVIEW

**Comment by abhaykv04** [comment]
I have read and hereby agree to quick-lint-js' Contributor License Agreement (CLA-v1.md).

**Comment by abhaykv04** [comment]
recheck

**Comment by strager** [comment]
This doesn't seem to fix the problem. The content still overflows with your patch applied.

Someone else contributed a better fix: #971

**Comment by abhaykv04** [comment]
@strager I conducted testing on my local machine and everything appeared to be functioning properly. Nonetheless, I acknowledge that the proposed solution, #971, may be more suitable. Thank you!

**Pull request closed without merging**
